import pandas as pd
import numpy as np

class SQLiMiner:
    def __init__(self, csv_file):
        # Load the data generated by the engine
        self.df = pd.read_csv(csv_file)
        
    def analyze_success_rates(self):
        """Uses Z-score to detect statistical outliers in response size/time."""
        if self.df.empty or len(self.df) < 2:
            return self.df

        # 1. Calculate Z-Score for response length
        mean_len = self.df['response_len'].mean()
        std_len = self.df['response_len'].std()
        
        if std_len == 0:
            self.df['is_content_success'] = False
        else:
            # Mark as success if the size is significantly different from the average
            self.df['z_score'] = (self.df['response_len'] - mean_len) / std_len
            self.df['is_content_success'] = self.df['z_score'].abs() > 1.0

        # 2. Flag Time-based success (anything 2 seconds slower than average)
        avg_time = self.df['response_time'].mean()
        self.df['is_time_success'] = self.df['response_time'] > (avg_time + 2)
        
        # Return only the rows that look like successful injections
        return self.df[self.df['is_content_success'] | self.df['is_time_success']]

    def get_summary_stats(self):
        """Calculates high-level metrics for the GUI counters."""
        # Check if we have data to analyze
        if self.df.empty:
            return {"total_attempts": 0, "anomalies_detected": 0, "avg_response_time": 0}

        # Identify anomalies using the analysis logic above
        success_df = self.analyze_success_rates()
        
        stats = {
            "total_attempts": len(self.df),
            "anomalies_detected": len(success_df),
            "avg_response_time": round(self.df['response_time'].mean(), 4)
        }
        return stats